config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'contacts/index'
  get 'tweets/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/index.html.erb
<h1>Contacts#index</h1>
<p>Find me in app/views/contacts/index.html.erb</p>
<% breadcrumb :contacts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breadcrumb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= breadcrumbs separator: " &rsaquo; " %>   
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p><%= link_to "コンタクトへ", contacts_index_path %></p>
<% breadcrumb :tweets %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p><%= link_to "ツイートへ", tweets_index_path %></p>
<% breadcrumb :root %>